### PR TITLE
Support JDK 11 and Xtext 2.16.0

### PR DESCRIPTION
**Pull request by franzbecker**

### CODE REVIEW

**Comment by cdietrich** [comment]
@franzbecker please note: for complete java 11 support we will need Xtext 2.17 which will be released on March 5th as of current planning.

**Comment by franzbecker** [comment]
@cdietrich language support or JDK 11 support? I ran the generator with JDK 11 and could spin up a Jetty with the Orion web editor without any problems. The language level that is configured in the project is still Java 8.

**Comment by cdietrich** [comment]
i mean: build with jdk 11 against java 8 target works on many paths, there are some (e.g. on mac) that dont work propertly.
build with java 11 target will work with Xtext 2.17 only

**Comment by franzbecker** [comment]
Okay thanks for the clarification. I tested this change with JDK 8 and 11 and both worked (on my machine). I think upgrading the generator in this way is still better than having the old generator which would always fail on JDK 11.

But we should definitely have another update once Xtext 2.17 is released.

**Pull request merged**
